export default {
  slippageCopy: 'Slippage is the difference between the estimated <br> and actual price you receive. The percentage you <br> select is the acceptable difference between the <br> current exchange rate and the exchange rate at <br> the time of your transaction\'s execution.',
  deposit: 'This deposits your selected tokens into the <br> exchange for swapping or adding to a liquidity pool.',
  nearDeposit: 'This first wraps then deposits your Ⓝ into the <br> exchange for swapping or adding to a liquidity pool.',
  nearWithdraw: 'This will first unwrap your Ⓝ then withdraw it from <br> the exchange and move the tokens to your wallet.',
  withdraw: 'This will withdraw your selected tokens from <br> the exchange and deposit them into your wallet.',
  registerToken: 'This registers a new token with the <br> exchange that is not already listed.',
  whitelistToken: 'This allows you to add an ERC-20 token to the exchange that is not already listed.',
  addLiquidityPool: 'This creates a new liquidity pool for the two tokens selected. <br> The fee is the percentage the pool takes from each transaction.',
  addLiquidity: 'This will deposit your tokens into the liquidity pool to <br> receive a portion of the returns this pool generates.',
  removeLiquidity: 'This removes your liquidity shares from the pool and <br> transfers the tokens back into your exchange portfolio.',
  swap: 'Swap exchanges the first selected token <br> with the value of the second selected token. <br> This looks for a pool with available liquidity <br> and the lowest exchange fee.',
  balances: 'This page reflects the amount of tokens you have deposited in the exchange. <br> Use the from below to add or withdraw tokens using your NEAR Wallet.',
  poolFee: 'The fee liquidity providers will earn on each trade. <br> If the fee is 0.3%, a trade of $100 nUSDT to nDAI <br> will incur a fee of $0.3 nDAI. This nDAI is distributed <br> proportionally to liquidity providers of the nUSDT - <br> nDAI pool',
  totalShares: 'Liquidity in the pool is represented as shares, rather than the tokens <br> themselves since the ratio of the tokens will change as traders swap. <br> For example, you may deposit 100 nDAI and 10 wNEAR and later remove <br> your liquidity and receive 150 nDAI and 5 wNEAR if the price of wNEAR is <br> increasing relative to nDAI.',
  underlyingLiquidity: 'The amount of each token currently in the pool.',
  totalLiquidity: 'Coming soon!',
  accVolume: 'Coming soon!',
  myUnderlyingLiquidity: 'Total amount of tokens you have in this pool.'
}