name: deploy-aws-us

on:
  push:
    branches: [ test-cicd ]
  pull_request:
    types:
      - closed
    branches: 
      - 'test-cicd'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: mydist
          path: './*'

  deploy-aws-us:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: mydist
          path: mydist

     


      - name: Execute SSH commmands on remote server[44.202.226.33]
        uses: appleboy/ssh-action@master
        with:
          host: 44.202.226.33
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD_01 }}
          port: 60022
          script: |
            cd /data/web/ref-ui-test
            # chown -R root:root /data/web/ref-ui-test
            # yarn install --frozen-lockfile
            # yarn build
            # yarn test
            # yarn prettier
 
            
     

      - name: Execute SSH commmands on remote server[3.238.218.91]
        uses: appleboy/ssh-action@master
        with:
          host: 3.238.218.91
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD_02 }}
          port: 60022
          script: |
            cd /data/web/ref-ui-test
            # chown -R root:root /data/web/ref-ui-test
            # yarn install --frozen-lockfile
            # yarn build
            # yarn test
            # yarn prettier


